sp_member_homepage:
    pattern:  /
    defaults: { _controller:SPMemberBundle:Member:index }

sp_member_view:
    pattern:  /{id}
    defaults: { _controller:SPMemberBundle:Member:view }
    requirements:
        id: \d+

sp_member_add:
    pattern:  /add
    defaults: { _controller:SPMemberBundle:Member:add }

sp_member_edit:
    pattern:  /edit/{id}
    defaults: { _controller:SPMemberBundle:Member:edit }
    requirements:
        id: \d+

sp_member_delete:
    pattern:  /delete/{id}
    defaults: { _controller:SPMemberBundle:Member:delete }
    requirements:
        id: \d+
