sp_member_homepage:
    pattern:  /member/
    defaults: { _controller:SPMemberBundle:Member:index }

sp_member_view:
    pattern:  /member/{id}
    defaults: { _controller:SPMemberBundle:Member:view }
    requirements:
        id: \d+

sp_member_add:
    pattern:  /member/add
    defaults: { _controller:SPMemberBundle:Member:add }

sp_member_edit:
    pattern:  /member/edit/{id}
    defaults: { _controller:SPMemberBundle:Member:edit }
    requirements:
        id: \d+

sp_member_delete:
    pattern:  /member/delete/{id}
    defaults: { _controller:SPMemberBundle:Member:delete }
    requirements:
        id: \d+

sp_company_homepage:
    pattern:  /company/
    defaults: { _controller:SPMemberBundle:Company:index }

sp_company_view:
    pattern:  /company/{id}
    defaults: { _controller:SPMemberBundle:Company:view }
    requirements:
        id: \d+

sp_company_add:
    pattern:  /company/add
    defaults: { _controller:SPMemberBundle:Company:add }

sp_company_edit:
    pattern:  /company/edit/{id}
    defaults: { _controller:SPMemberBundle:Company:edit }
    requirements:
        id: \d+

sp_company_delete:
    pattern:  /company/delete/{id}
    defaults: { _controller:SPMemberBundle:Company:delete }
    requirements:
        id: \d+

sp_product_homepage:
    pattern:  /product/
    defaults: { _controller:SPMemberBundle:Product:index }

sp_product_view:
    pattern:  /product/{id}
    defaults: { _controller:SPMemberBundle:Product:view }
    requirements:
        id: \d+

sp_product_add:
    pattern:  /product/add
    defaults: { _controller:SPMemberBundle:Product:add }

sp_product_edit:
    pattern:  /product/edit/{id}
    defaults: { _controller:SPMemberBundle:Product:edit }
    requirements:
        id: \d+

sp_product_delete:
    pattern:  /product/delete/{id}
    defaults: { _controller:SPMemberBundle:Product:delete }
    requirements:
        id: \d+

sp_orderline_homepage:
    pattern:  /order/
    defaults: { _controller:SPMemberBundle:OrderLine:index }

sp_orderline_view:
    pattern:  /order/{id}
    defaults: { _controller:SPMemberBundle:OrderLine:view }
    requirements:
        id: \d+

sp_orderline_add:
    pattern:  /order/add
    defaults: { _controller:SPMemberBundle:OrderLine:add }

sp_orderline_edit:
    pattern:  /order/edit/{id}
    defaults: { _controller:SPMemberBundle:OrderLine:edit }
    requirements:
        id: \d+

sp_orderline_delete:
    pattern:  /order/delete/{id}
    defaults: { _controller:SPMemberBundle:OrderLine:delete }
    requirements:
        id: \d+

sp_orderline_logging:
    pattern:  /order/logg/{id}
    defaults: { _controller:SPMemberBundle:OrderLine:logging }
    requirements:
        id: \d+
