sp_member_homepage:
    pattern:  /member
    defaults: { _controller:SPMemberBundle:Member:index }

sp_member_view:
    pattern:  /member/{id}
    defaults: { _controller:SPMemberBundle:Member:view }
    requirements:
        id: \d+

sp_member_add:
    pattern:  /member/add
    defaults: { _controller:SPMemberBundle:Member:add }

sp_member_edit:
    pattern:  /member/edit/{id}
    defaults: { _controller:SPMemberBundle:Member:edit }
    requirements:
        id: \d+

sp_member_delete:
    pattern:  /member/delete/{id}
    defaults: { _controller:SPMemberBundle:Member:delete }
    requirements:
        id: \d+
