sp_member:
    resource: "@SPMemberBundle/Resources/config/routing.yml"
    prefix:   /member

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
